<?php

declare(strict_types=1);

/**
 * Regenerates src/Website/Catalog/Geo/postal-centroids.php from the GeoNames
 * postal-code dump for Germany.
 *
 * The dump is NOT tracked in this repository (it is ~5 MB). Download it fresh
 * when you need to regenerate the table:
 *
 *   curl -sSLO https://download.geonames.org/export/zip/DE.zip
 *   unzip -o DE.zip DE.txt
 *   php tools/geo/build-plz-centroids.php DE.txt
 *
 * Source: GeoNames (https://www.geonames.org/), licensed CC BY 4.0. The public
 * map page credits GeoNames as required by that licence.
 *
 * The dump has one tab-separated row per (postal code, place, admin area). For
 * each five-digit postal code we keep the mean latitude/longitude of its rows;
 * for each three-digit prefix we keep the mean of every code beneath it, used
 * as a fallback when a drink's exact postal code is not in the dump.
 */

if (PHP_SAPI !== 'cli') {
    fwrite(STDERR, "CLI only.\n");
    exit(1);
}

$source = $argv[1] ?? null;

if (!is_string($source) || !is_file($source)) {
    fwrite(STDERR, "Usage: php tools/geo/build-plz-centroids.php <path-to-DE.txt>\n");
    exit(1);
}

$handle = fopen($source, 'r');

if ($handle === false) {
    fwrite(STDERR, "Cannot open {$source}.\n");
    exit(1);
}

/** @var array<string, array{lat: float, lon: float, n: int}> $codes */
$codes = [];

while (($line = fgets($handle)) !== false) {
    $fields = explode("\t", rtrim($line, "\r\n"));

    if (count($fields) < 11) {
        continue;
    }

    [$postalCode, $latitude, $longitude] = [$fields[1], $fields[9], $fields[10]];

    if (preg_match('/^\d{5}$/', $postalCode) !== 1 || !is_numeric($latitude) || !is_numeric($longitude)) {
        continue;
    }

    $codes[$postalCode] ??= ['lat' => 0.0, 'lon' => 0.0, 'n' => 0];
    $codes[$postalCode]['lat'] += (float) $latitude;
    $codes[$postalCode]['lon'] += (float) $longitude;
    ++$codes[$postalCode]['n'];
}

fclose($handle);

if ($codes === []) {
    fwrite(STDERR, "No usable rows found in {$source}.\n");
    exit(1);
}

ksort($codes, SORT_STRING);

/** @var array<string, array{0: float, 1: float}> $exact */
$exact = [];
/** @var array<string, array{lat: float, lon: float, n: int}> $prefixAccumulator */
$prefixAccumulator = [];

foreach ($codes as $postalCode => $sum) {
    $postalCode = (string) $postalCode;
    $lat = round($sum['lat'] / $sum['n'], 4);
    $lon = round($sum['lon'] / $sum['n'], 4);
    $exact[$postalCode] = [$lat, $lon];

    $prefix = substr($postalCode, 0, 3);
    $prefixAccumulator[$prefix] ??= ['lat' => 0.0, 'lon' => 0.0, 'n' => 0];
    $prefixAccumulator[$prefix]['lat'] += $lat;
    $prefixAccumulator[$prefix]['lon'] += $lon;
    ++$prefixAccumulator[$prefix]['n'];
}

ksort($prefixAccumulator, SORT_STRING);

/** @var array<string, array{0: float, 1: float}> $prefix */
$prefix = [];

foreach ($prefixAccumulator as $key => $sum) {
    $prefix[$key] = [round($sum['lat'] / $sum['n'], 4), round($sum['lon'] / $sum['n'], 4)];
}

$number = static function (float $value): string {
    $formatted = rtrim(sprintf('%.4f', $value), '0');

    return str_ends_with($formatted, '.') ? $formatted . '0' : $formatted;
};

$export = static function (array $table, string $indent) use ($number): string {
    $lines = [];

    foreach ($table as $key => [$lat, $lon]) {
        $lines[] = sprintf("%s'%s' => [%s, %s],", $indent, (string) $key, $number($lat), $number($lon));
    }

    return implode("\n", $lines);
};

$generated = "<?php\n\n"
    . "declare(strict_types=1);\n\n"
    . "/**\n"
    . " * Postal-code centroids for Germany, generated by tools/geo/build-plz-centroids.php\n"
    . " * from the GeoNames postal-code dump (https://www.geonames.org/, CC BY 4.0).\n"
    . " *\n"
    . " * Do not edit by hand. 'exact' is keyed by five-digit postal code, 'prefix' by\n"
    . " * the three-digit Leitregion prefix and used as a fallback. Every value is\n"
    . " * [latitude, longitude], rounded to four decimal places (~11 m).\n"
    . " */\n\n"
    . "return [\n"
    . "    'exact' => [\n" . $export($exact, '        ') . "\n    ],\n"
    . "    'prefix' => [\n" . $export($prefix, '        ') . "\n    ],\n"
    . "];\n";

$target = dirname(__DIR__, 2) . '/src/Website/Catalog/Geo/postal-centroids.php';
file_put_contents($target, $generated);

fwrite(STDOUT, sprintf(
    "Wrote %s\n  %d postal codes, %d three-digit prefixes\n",
    $target,
    count($exact),
    count($prefix),
));
