<?php

declare(strict_types=1);

/**
 * Regenerates src/Website/Catalog/Geo/place-centroids.php — the town-name index
 * behind the "PLZ oder Ort" search on the hunt map.
 *
 * Built from the GeoNames main gazetteer for Germany (NOT the postal dump). It
 * is ~30 MB and not tracked here; download it fresh to regenerate:
 *
 *   curl -sSLO https://download.geonames.org/export/dump/DE.zip
 *   unzip -o DE.zip DE.txt
 *   php tools/geo/build-place-centroids.php DE.txt
 *
 * Source: GeoNames (https://www.geonames.org/), CC BY 4.0 — credited on the map.
 *
 * Only populated places (feature class P) with a recorded population of at
 * least 1000 are kept; smaller places are found through their postal code
 * instead. Each place is indexed under its own name, its ASCII name and its
 * short latin alternate names (so "München", "Munchen" and "Munich" all match),
 * normalised the same way as the search input. When two places share a
 * normalised key, the more populous one wins.
 */

if (PHP_SAPI !== 'cli') {
    fwrite(STDERR, "CLI only.\n");
    exit(1);
}

$source = $argv[1] ?? null;

if (!is_string($source) || !is_file($source)) {
    fwrite(STDERR, "Usage: php tools/geo/build-place-centroids.php <path-to-gazetteer-DE.txt>\n");
    exit(1);
}

$handle = fopen($source, 'r');

if ($handle === false) {
    fwrite(STDERR, "Cannot open {$source}.\n");
    exit(1);
}

$featureCodes = array_flip(['PPL', 'PPLA', 'PPLA2', 'PPLA3', 'PPLA4', 'PPLA5', 'PPLC', 'PPLX', 'PPLL']);
$minPopulation = 1000;
$displayOverride = ['Munich' => 'München', 'Nuremberg' => 'Nürnberg', 'Cologne' => 'Köln'];

$normalise = static function (string $value): string {
    $value = mb_strtolower(trim($value), 'UTF-8');
    $value = strtr($value, ['ä' => 'ae', 'ö' => 'oe', 'ü' => 'ue', 'ß' => 'ss']);

    return (string) preg_replace('/[^a-z0-9]+/', '', $value);
};

$isPlausibleName = static function (string $value): bool {
    return mb_strlen($value) <= 30
        && substr_count($value, ' ') <= 2
        && preg_match('/^[A-Za-z0-9ÄÖÜäöüß .\/()\'-]+$/u', $value) === 1;
};

/** @var array<string, array{0: float, 1: float, 2: string, 3: int}> $best */
$best = [];

while (($line = fgets($handle)) !== false) {
    $fields = explode("\t", $line);

    if (count($fields) < 15 || ($fields[6] ?? '') !== 'P' || !isset($featureCodes[$fields[7] ?? ''])) {
        continue;
    }

    $population = (int) $fields[14];

    if ($population < $minPopulation) {
        continue;
    }

    $latitude = round((float) $fields[4], 4);
    $longitude = round((float) $fields[5], 4);
    $display = $displayOverride[$fields[1]] ?? $fields[1];

    $names = [$fields[1], $fields[2]];

    if (($fields[3] ?? '') !== '') {
        $names = array_merge($names, explode(',', $fields[3]));
    }

    foreach ($names as $name) {
        $name = trim($name);

        if ($name === '' || !$isPlausibleName($name)) {
            continue;
        }

        $key = $normalise($name);

        if (strlen($key) < 2) {
            continue;
        }

        if (!isset($best[$key]) || $population > $best[$key][3]) {
            $best[$key] = [$latitude, $longitude, $display, $population];
        }
    }
}

fclose($handle);

if ($best === []) {
    fwrite(STDERR, "No usable places found in {$source}.\n");
    exit(1);
}

ksort($best, SORT_STRING);

$number = static function (float $value): string {
    $formatted = rtrim(sprintf('%.4f', $value), '0');

    return str_ends_with($formatted, '.') ? $formatted . '0' : $formatted;
};

$rows = [];

foreach ($best as $key => [$latitude, $longitude, $display]) {
    $rows[] = sprintf(
        '    %s => [%s, %s, %s],',
        var_export($key, true),
        $number($latitude),
        $number($longitude),
        var_export($display, true),
    );
}

$generated = "<?php\n\n"
    . "declare(strict_types=1);\n\n"
    . "/**\n"
    . " * Town-name search index for Germany, generated by\n"
    . " * tools/geo/build-place-centroids.php from the GeoNames gazetteer\n"
    . " * (https://www.geonames.org/, CC BY 4.0). Do not edit by hand.\n"
    . " *\n"
    . " * Keyed by the normalised place name; value is\n"
    . " * [latitude, longitude, display name].\n"
    . " */\n\n"
    . "return [\n"
    . implode("\n", $rows) . "\n"
    . "];\n";

$target = dirname(__DIR__, 2) . '/src/Website/Catalog/Geo/place-centroids.php';
file_put_contents($target, $generated);

fwrite(STDOUT, sprintf("Wrote %s\n  %d place keys\n", $target, count($best)));
